### PR TITLE
When using an indicator, there are cases in which the contents are se…

### PR DESCRIPTION
**Pull request by TejNote**
…arched in units of 20 when searching the API.

At this time, it is necessary to express the number of all contents on the indicator.
So, it was additionally processed with a variable called maxDotCount.

1. add maxDotCount variable
2. add setMaxDotCount method
3. modify getItemCount method

### CODE REVIEW

**Comment by wching** [comment]
Hello @TejNote, thanks for the patience!
Question, even when you set the max from the start, the user wouldn't be able to see all, right? Why don't you limit the amount of items that you pass to the adapter itself? I'm having a hard time understanding why the library should handle this because if there are more/less items it will look weird.

**Comment by wching** [comment]
Closing as I got no answer back and I don't find a strong reason for this to be handled by the lib.

**Comment by TejNote** [comment]
Sorry. I couldn't check the mail, so I saw it now.
The reason for the need for this function is that when searching for items through API, there are cases in which 20 items are searched by dividing them into pages. At this time, the actual number of items is 300, but since it is divided into pages, maxDotCount is set to 300 in advance, and when 20 items are displayed, an additional 20 items are searched and the corresponding modification was made to add additional items.

I can't speak English, so I'm sorry if there's anything awkward when I use Google Translate.

**Comment by wching** [comment]
> I can't speak English, so I'm sorry if there's anything awkward when I use Google Translate.

No worries at all 😄 

> At this time, the actual number of items is 300, but since it is divided into pages, maxDotCount is set to 300 in advance

But why are you setting 300 items right away?
If you receive the total amount of items as a field in the response of the request, and you only have 20, then why don't you use just the 20 that already has? You are not forced to set the 300 right away. Just set what you have at the moment and I think you problem is gone. What do you think?

**Comment by TejNote** [comment]
https://medium.com/swlh/paginating-requests-in-apis-d4883d4c1c4c

When looking at the referenced URL, there is a situation where it is called and displayed for each page.
At this time, the total number was shown, and in reality, we tried to minimize network resources by searching by page.
If you don't do that, you have to search all 300 immediately when searching the API, which consumes a lot of network resources. So, I tried to use a method of efficiently telling the user that there are 300 items, and searching 20 items in advance and inserting data while moving the page.

**Comment by wching** [comment]
@TejNote ok, I understand the issue and your solution, but you will never be able to see the 300 dots, right? Why doesn't using setCount with a value of 300 work?

**Comment by TejNote** [comment]
Good morning. @wching 
Is the setCount you told me about setDotCount right?
I understand setCount as a value that sets the number of displays at once.
However, what I wanted to do was to show only 5 dots, and to let the user know that there is more behind them even if they scroll.

For example, if you search 1 page and only 20 are added, and setDotCount to 5, when you go to the 20th position, it appears as if there is no dot behind it.
However, with setMaxDotCount, more dots appear regardless of the actual number of items, so the user can recognize that there is more content behind them.

**Comment by wching** [comment]
Hey @TejNote, after thinking about it, I feel that this ft adds unexpected future behaviors. This component relies completely on the android views as the source of truth and I think the current solution doesn't take that into consideration. What happens when you set a max of 1000 and the current android view has just 10 items and you don't handle this? Could you think of another solution that takes this scenario into consideration?

**Pull request closed without merging**
