### PR TITLE
Update gradle & kotlin versions

### PR DESCRIPTION
**Pull request by paul-turner**
Was getting some noise in build logs over the kotlin stdlib dependency:
`warning: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead`
This bumps up the kotlin and gradle versions to the latest stable.

### CODE REVIEW

**Comment by rbro112** [comment]
@paul-turner thanks for the help! Sorry for the delay, been out of the country for awhile. I'll review tonight after I get off work!

**Comment by rbro112** [comment]
@paul-turner Looks and works great! Merging in then pushing to maven. Changes will be reflected as version 1.0.9.

Hope everything's great over at BNR!

**Comment by Shounak** [comment]
@rbro112 Paul's at Mailchimp now 😃

**Comment by Shounak** [comment]
He has joined the dark side

**Comment by rbro112** [comment]
@Shounak haha another BNR dev gone to Mailchimp, congrats @paul-turner!

**Pull request merged**
